### PR TITLE
Add upgrade for rename getUsername to getUserIdentifier

### PR DESCRIPTION
**Pull request by alexander-schranz**
This will already rename the sulu users `getUsername` to `getUserIdentifier`.

Try out this PR by copy following in your unix shell:

Upgrade for: https://github.com/sulu/sulu/pull/6626

```bash
git clone git@github.com:sulu/sulu-rector.git
cd sulu-rector/
git remote add alex git@github.com:alexander-schranz/sulu-rector.git
git fetch alex
git checkout feature/replace-user-name-with-user-identifier-method
composer install
composer test
```

### CODE REVIEW

**Comment by alexander-schranz** [comment]
I don't get why this is failing in the CI 🤔 it seems to work correctly locally.

**Comment by alexander-schranz** [comment]
@TomasVotruba Sorry for pinging you but I'm little bot lost again. Do you have any hint what is going wrong here? It works locally for me:

```bash
git clone git@github.com:sulu/sulu-rector.git
cd sulu-rector/
git remote add alex git@github.com:alexander-schranz/sulu-rector.git
git fetch alex
git checkout feature/replace-user-name-with-user-identifier-method
composer install
composer test
```

but the rule just don't work in the CI which is very strange. Even checked if the CI installs other dependencies but they are the same. Also did `cat` the files the looks also correclty in the CI not sure what is going wrong here. Even updated the composer install actions still the rule test does not work in the CI.

**Comment by TomasVotruba** [comment]
I've just tested for a while locally to find this fix: https://github.com/rectorphp/rector-src/commit/cbebb9a4de7d15fedd55d5035c11603397c85c27

Basically this rename would break parent interface contract. Untill the Symfony require parent interface, the method rename would cause a BC break:

```bash
public function getUsername();
```

Yet, in this case, the change could be done in an interface :+1: I'll see if we can improve it

**Comment by TomasVotruba** [comment]
This should help: https://github.com/rectorphp/rector-src/pull/2362

Could you try rector dev-main?

**Comment by TomasVotruba** [comment]
See https://github.com/sulu/sulu-rector/pull/8

**Pull request closed without merging**
