### PR TITLE
Add few more dashes

### PR DESCRIPTION
**Pull request by TomasVotruba**

### CODE REVIEW

**Comment by alexander-schranz** [comment]
@TomasVotruba Thank you ❤️

**Comment by TomasVotruba** [comment]
You're welcome :+1: 

I can say you've done the setup propperly, the config and the tests are as they should be, so is the autoloading.
One little improvement can be using correct PSR-4 namespace in a test class (now there is Symfony, probably from old copy-paste), and in test fixture files. PHPStan can in some cases mix two `class SomeClass {}` from different locations. So it(s better to separate them by fixture namespace.

But that's just little detail that might help you later on. Otherwise very good job :clap:

**Comment by alexander-schranz** [comment]
Thank you for your feedback 😃. 

I really like the test setup you created here, it make it really easy to write tests. I cloned the setup for my other project a test-generator which tests work the same way. Example [here](https://github.com/alexander-schranz/test-generator/blob/main/tests/Model/SetGet/Fixture/model_with_set_get_datetime.php). And inspired by your setup using markdown for API tests which work the same way [here](https://github.com/alexander-schranz/markdown-based-api-testing).

Add a namespace make sense. Did fix that and the Namespace in https://github.com/sulu/sulu-rector/pull/3.

**Comment by alexander-schranz** [comment]
@TomasVotruba Nice, thank you for sharing. I also thought about the update thing, because I know it from Jest which has also this kind of snapshots tests: https://jestjs.io/docs/snapshot-testing. And they also have this kind of flag to update the tests via a additional flag.

**Pull request merged**
